"""Deterministic Markdown rendering for GVE level specifications."""

from __future__ import annotations

from typing import Any, Mapping


def render_markdown(document: Mapping[str, Any]) -> str:
    specification = document["specification"]
    parent = (
        "None"
        if specification["parent"] is None
        else f"`{specification['parent']}`"
    )
    source_name = f"{specification['id']}.json"
    lines = [
        f"# {specification['title']}",
        "",
        f"> Generated deterministically from `{source_name}`. Do not edit this file independently.",
        "",
        f"**Specification:** `{specification['id']}`<br>",
        f"**Level:** {specification['level']}<br>",
        f"**Version:** {specification['version']}<br>",
        f"**Status:** {specification['status']}<br>",
        f"**Parent:** {parent}",
    ]
    metadata = document.get("document")
    if metadata is not None:
        imports = (
            ", ".join(f"`{identifier}`" for identifier in metadata["imports"])
            or "None"
        )
        lines.extend(
            [
                f"<br>**Document role:** {metadata['role']}<br>",
                f"**Specification-set root:** `{metadata['root']}`<br>",
                f"**Imports:** {imports}",
            ]
        )
    lines.extend(
        [
            "",
            "## Summary",
            "",
            document["summary"],
            "",
            "## Definitions",
            "",
        ]
    )
    for item in document["definitions"]:
        lines.extend(
            [
                f"### {item['term']} (`{item['id']}`)",
                "",
                item["text"],
                "",
            ]
        )
    lines.extend(["## Normative requirements", ""])
    for item in document["requirements"]:
        references = (
            ", ".join(f"`{reference}`" for reference in item["references"])
            or "None"
        )
        lines.extend(
            [
                f"### {item['id']}",
                "",
                item["text"],
                "",
                f"References: {references}",
                "",
            ]
        )
    lines.extend(["## Relationships", ""])
    for item in document["relationships"]:
        lines.append(
            f"- `{item['id']}`: `{item['source']}` "
            f"**{item['relation']}** `{item['target']}`"
        )
    lines.extend(["", "## Scope", "", "### Includes", ""])
    for item in document["scope"]["includes"]:
        lines.append(f"- {item}")
    lines.extend(["", "### Excludes", ""])
    for item in document["scope"]["excludes"]:
        lines.append(f"- {item}")
    lines.append("")
    return "\n".join(lines)
